version: "3.9"
services:
  app:
    build: .
    ports:
      - "10000:10000"
    depends_on:
      - mysql
    environment:
      - ConnectionStrings__DefaultConnection=server=mysql;port=3306;database=siresu_db;user=root;password=12345;

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: siresu_db
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
